/**
 * Admin Routes Aggregator
 * Combines all admin routes
 * 
 * @module admin/routes/index
 */

const express = require('express');
const router = express.Router();

// Import middleware
const { adminAuthMiddleware, adminRoleMiddleware } = require('../middleware/adminAuth');

// Import routes
const adminAuthRoutes = require('./adminAuthRoutes');
const adminDashboardRoutes = require('./adminDashboardRoutes');
const adminProductRoutes = require('./adminProductRoutes');
const adminOrderRoutes = require('./adminOrderRoutes');
const adminUserRoutes = require('./adminUserRoutes');

// Import controllers
const {
    categoryController,
    couponController,
    inventoryController,
    reportController,
    settingsController
} = require('../controllers/adminMiscController');

// ============================================
// AUTH ROUTES (public - login is public)
// ============================================
router.use('/auth', adminAuthRoutes);

// ============================================
// PROTECTED ROUTES (all require authentication)
// ============================================

// Apply authentication middleware to all protected routes
router.use(adminAuthMiddleware);

// Dashboard routes
router.use('/dashboard', adminDashboardRoutes);

// Product routes
router.use('/products', adminProductRoutes);

// Order routes
router.use('/orders', adminOrderRoutes);

// User routes
router.use('/users', adminUserRoutes);

// ============================================
// CATEGORY ROUTES
// ============================================
router.get('/categories', categoryController.getAll);
router.post('/categories', categoryController.create);
router.get('/categories/:id', categoryController.getById);
router.put('/categories/:id', categoryController.update);
router.delete('/categories/:id', categoryController.delete);

// ============================================
// COUPON ROUTES
// ============================================
router.get('/coupons', couponController.getAll);
router.post('/coupons', couponController.create);
router.get('/coupons/:id', couponController.getById);
router.put('/coupons/:id', couponController.update);
router.delete('/coupons/:id', couponController.delete);

// ============================================
// INVENTORY ROUTES
// ============================================
router.get('/inventory', inventoryController.getStatus);
router.get('/inventory/alerts', inventoryController.getAlerts);
router.get('/inventory/logs', inventoryController.getLogs);
router.post('/inventory/adjust', inventoryController.adjustStock);
router.put('/inventory/reorder-level', inventoryController.setReorderLevel);

// ============================================
// REPORTS & EXPORTS ROUTES
// ============================================
router.get('/reports/sales', reportController.getSales);
router.get('/reports/products', reportController.getProducts);
router.get('/reports/users', reportController.getUsers);
router.get('/reports/inventory', reportController.getInventory);

// Export orders spreadsheet (downloads current Excel file)
router.get('/exports/orders', reportController.exportOrders);
// Export users spreadsheet generated by user service
router.get('/exports/users', reportController.exportUsers);

// ============================================
// SETTINGS ROUTES
// ============================================
router.get('/settings', settingsController.get);
router.put('/settings', settingsController.update);
router.get('/settings/payment', settingsController.getPayment);
router.put('/settings/payment', settingsController.updatePayment);

module.exports = router;
